### ISSUE TITLE
Crashes when image extension doesn't match image type

### ISSUE THREAD

**Issue by patclay** [DivaVocals/zen_Image-Handler#19] opened 2017-08-02 03:50 UTC
If you create a png file mistake.png , then rename it to mistake.jpg, add it to a product, then this causes problems.

The product page will not show the price/add to cart buttons.  Also, in my implementation at least, it messes up the product before due to the fetch next product image function crashing as well.  The product search results page is also similarly killed.

Unfortunately it doesn't leave any trace in the logs either.

**Comment by lat9** [comment] 2017-10-13 17:46
I'm unable to reproduce this issue on the current (5.0.0-beta3) version.  What are your IH settings?  Are you using the GD libraries or ImageMagick?

**Comment by patclay** [comment] 2017-10-17 21:49
From phpinfo:


imagick module version | 3.2.0RC1
-- | --
imagick classes | Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator
ImageMagick version | ImageMagick 6.8.9-9 Q16 x86_64 2017-07-15 http://www.imagemagick.org


GD Support | enabled
-- | --
GD headers Version | 2.1.1-dev

Which IH settings are you looking for?

**Comment by lat9** [comment] 2017-10-18 19:13
Pat, thanks for the update.  I sent a PM to you (I think) on the Zen Cart forums.  I don't have any installations that include ImageMagick to attempt to reproduce this error and would appreciate access to the site in question for debug.

**Comment by lat9** [comment] 2017-10-21 12:58
Removed that unreproducible label and noted this as a bug.  The issue will be addressed in a point-release, once the base IH5 update is published.

**Comment by lat9** [comment] 2023-02-05 15:44
I normally keep issues open until they're released.

**Closed** 2023-03-07 14:07 UTC
Labels: bug, fix provided
